version: '1'
services:
  innotas_water_decoder:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MODULE_NAME: Innotas Water Sensor Decoder
      EGRESS_URL: https://testmp.free.beeceptor.com/
      INGRESS_HOST: 127.0.0.1
      INGRESS_PORT: 80
