version: "3.0"
services:
  innotas-water-meter-decoder:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "Innotas Water Sensor Decoder"
      MODULE_TYPE: "Processing"
      EGRESS_URLS: "https://testdockercompose.free.beeceptor.com"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      NESTED_RESPONSE: 'no'
    ports:
      - 80:80